### ISSUE TITLE
 error: SyntaxError: Unexpected reserved word : /node_modules/authorizenet/lib/apicontracts.js:7

### ISSUE THREAD

**Issue by vaibhavangelstec** [AuthorizeNet/sdk-node#34]
Getting error in authorizenet npm module, after installation not able to reboot my site.
Getting error:
/node_modules/authorizenet/lib/apicontracts.js:7
class ANetApiRequest {
^^^^^
2018-06-15T10:11:04.096Z - error: Unexpected reserved word
2018-06-15T10:11:04.098Z - error: SyntaxError: Unexpected reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/EventsLocker-master/node_modules/authorizenet/lib/authorizenet.js:4:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/EventsLocker-master/backend/controllers/checkoutController.js:6:20)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

![image](https://user-images.githubusercontent.com/22920732/41463123-eb4e780e-70b2-11e8-94c2-8f57b941fee9.png)

**Comment by chsriniv9** [comment]
@vaibhavangelstec 
This error is because the version of Node.JS does not meet the requirements mentioned in README.md. As per this requirement, Node.JS must have version 4.8.4 or higher. Kindly upgrade Node.JS to resolve this issue.

**Comment by chsriniv9** [comment]
@vaibhavangelstec, required information on the minimum version supported for Node.JS is provided in the previous post and assume it had helped to address the reported issue, hence closing this issue. Please feel free to reopen if any further support needed.
